### PR TITLE
Return an error message to the UI

### LINKED ISSUE #9: Improve error reporting when server is unavailable
If a request fails form any reason (server unavailable, network error, etc.), the app show a quite not-descriptive error from the library: `Door opening failed: DioError`.

Can we improve a little bit on error reporting? Does the network library returns something more useful? Ideally the user should see something like:
- `Door opening failed: server unreachable`
- `Door opening failed: network error`

### PR DESCRIPTION
**Pull request by apiraino**
r? @axellebot

I tried to extract a human readable error message from the `state.error` but I couldn't figure out how, so I've added another field with the error message.

The message is still a bit obscure but a bit better than a generic "DioError".

I'd welcome suggestions on how to improve this patch :-) otherwise I'd merge it

Should fix #9

### CODE REVIEW

File: lib/src/domain/blocs/door/door_state.dart [hunk 1]
```diff
@@ -25,9 +25,10 @@ class DoorSucceed extends DoorState {
...
 class DoorFailure extends DoorState {
   final Error error;
+  final String message;
 
-  DoorFailure({@required this.error}) : super([error]);
+  DoorFailure({@required this.error, @required this.message}) : super([error]);
 
   @override
-  String toString() => '$runtimeType{ error: $error }';
+  String toString() => '$runtimeType{ error: $error }: $message ';
```
Comment (axellebot) [inline lib/src/domain/blocs/door/door_state.dart]: Should keep Json format like this : `$runtimeType{ error: $error , message: $message }`
(But the message field will be remove by https://github.com/apiraino/open-taffeta-mobile-app/pull/10#discussion_r300704455)

File: lib/src/ui/pages/home_page.dart [hunk 2]
```diff
@@ -86,7 +86,7 @@ class __AuthenticatedHomeState extends State<_AuthenticatedHome> {
           Scaffold.of(context).showSnackBar(
             SnackBar(
               content: Text(
-                  '${BuzzerLocalizations.of(context).buzzerDoorFailed} : ${state.error.runtimeType}'),
+                  '${BuzzerLocalizations.of(context).buzzerDoorFailed} : ${ state.message }'),
```
Comment (axellebot) [inline lib/src/ui/pages/home_page.dart]: Should be replace by ` '${BuzzerLocalizations.of(context).buzzerDoorFailed} : ${state.error.message??state.error.runtimeType}'),` instead of adding a message field that can be known from the `error` property already part of the `state` :)

**Review by axellebot — CHANGES_REQUESTED** [review]
